import type { Locale, PlanetId } from "@/lib/types";

export const RASHIS: Record<Locale, string[]> = {
  en: [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
  ],
  te: [
    "మేషం",
    "వృషభం",
    "మిథునం",
    "కర్కాటకం",
    "సింహం",
    "కన్య",
    "తులా",
    "వృశ్చికం",
    "ధనుస్సు",
    "మకరం",
    "కుంభం",
    "మీనం",
  ],
  hi: [
    "मेष",
    "वृषभ",
    "मिथुन",
    "कर्क",
    "सिंह",
    "कन्या",
    "तुला",
    "वृश्चिक",
    "धनु",
    "मकर",
    "कुंभ",
    "मीन",
  ],
  ta: [
    "மேஷம்",
    "ரிஷபம்",
    "மிதுனம்",
    "கடகம்",
    "சிம்மம்",
    "கன்னி",
    "துலாம்",
    "விருச்சிகம்",
    "தனுஷு",
    "மகரம்",
    "கும்பம்",
    "மீனம்",
  ],
  mr: [
    "मेष",
    "वृषभ",
    "मिथुन",
    "कर्क",
    "सिंह",
    "कन्या",
    "तुळ",
    "वृश्चिक",
    "धनु",
    "मकर",
    "कुंभ",
    "मीन",
  ],
  kn: [
    "ಮೇಷ",
    "ವೃಷಭ",
    "ಮಿಥುನ",
    "ಕರ್ಕ",
    "ಸಿಂಹ",
    "ಕನ್ಯಾ",
    "ತುಲಾ",
    "ವೃಶ್ಚಿಕ",
    "ಧನು",
    "ಮಕರ",
    "ಕುಂಭ",
    "ಮೀನ",
  ],
};

export const NAKSHATRAS: Record<Locale, string[]> = {
  en: [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
  ],
  te: [
    "అశ్విని",
    "భరణి",
    "కృత్తిక",
    "రోహిణి",
    "మృగశిర",
    "ఆర్ద్ర",
    "పునర్వసు",
    "పుష్య",
    "ఆశ్లేష",
    "మఘ",
    "పూర్వ ఫల్గుణి",
    "ఉత్తర ఫల్గుణి",
    "హస్త",
    "చిత్ర",
    "స్వాతి",
    "విశాఖ",
    "అనురాధ",
    "జ్యేష్ఠ",
    "మూల",
    "పూర్వాషాఢ",
    "ఉత్తరాషాఢ",
    "శ్రవణం",
    "ధనిష్ఠ",
    "శతభిష",
    "పూర్వ భాద్రపద",
    "ఉత్తర భాద్రపద",
    "రేవతి",
  ],
  hi: [
    "अश्विनी",
    "भरणी",
    "कृत्तिका",
    "रोहिणी",
    "मृगशिरा",
    "आर्द्रा",
    "पुनर्वसु",
    "पुष्य",
    "आश्लेषा",
    "मघा",
    "पूर्व फाल्गुनी",
    "उत्तर फाल्गुनी",
    "हस्त",
    "चित्रा",
    "स्वाति",
    "विशाखा",
    "अनुराधा",
    "ज्येष्ठा",
    "मूल",
    "पूर्वाषाढ़ा",
    "उत्तराषाढ़ा",
    "श्रवण",
    "धनिष्ठा",
    "शतभिषा",
    "पूर्व भाद्रपद",
    "उत्तर भाद्रपद",
    "रेवती",
  ],
  ta: [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "Purva Phalguni",
    "Uttara Phalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "Purva Ashadha",
    "Uttara Ashadha",
    "Shravana",
    "Dhanishta",
    "Shatabhisha",
    "Purva Bhadrapada",
    "Uttara Bhadrapada",
    "Revati",
  ],
  mr: [
    "अश्विनी",
    "भरणी",
    "कृत्तिका",
    "रोहिणी",
    "मृगशिरा",
    "आर्द्रा",
    "पुनर्वसु",
    "पुष्य",
    "आश्लेषा",
    "मघा",
    "पूर्व फाल्गुनी",
    "उत्तर फाल्गुनी",
    "हस्त",
    "चित्रा",
    "स्वाती",
    "विशाखा",
    "अनुराधा",
    "ज्येष्ठा",
    "मूल",
    "पूर्वाषाढा",
    "उत्तराषाढा",
    "श्रवण",
    "धनिष्ठा",
    "शतभिषा",
    "पूर्व भाद्रपद",
    "उत्तर भाद्रपद",
    "रेवती",
  ],
  kn: [
    "ಅಶ್ವಿನಿ",
    "ಭರಣಿ",
    "ಕೃತ್ತಿಕ",
    "ರೋಹಿಣಿ",
    "ಮೃಗಶಿರ",
    "ಆರ್ದ್ರ",
    "ಪುನರ್ವಸು",
    "ಪುಷ್ಯ",
    "ಆಶ್ಲೇಷ",
    "ಮಘ",
    "ಪೂರ್ವ ಫಲ್ಗುಣಿ",
    "ಉತ್ತರ ಫಲ್ಗುಣಿ",
    "ಹಸ್ತ",
    "ಚಿತ್ರ",
    "ಸ್ವಾತಿ",
    "ವಿಶಾಖ",
    "ಅನುರಾಧ",
    "ಜ್ಯೇಷ್ಠ",
    "ಮೂಲ",
    "ಪೂರ್ವಾಷಾಢ",
    "ಉತ್ತರಾಷಾಢ",
    "ಶ್ರವಣ",
    "ಧನಿಷ್ಠ",
    "ಶತಭಿಷ",
    "ಪೂರ್ವ ಭಾದ್ರಪದ",
    "ಉತ್ತರ ಭಾದ್ರಪದ",
    "ರೇವತಿ",
  ],
};

export const PLANET_LABELS: Record<Locale, Record<PlanetId, string>> = {
  en: {
    sun: "Sun",
    moon: "Moon",
    mars: "Mars",
    mercury: "Mercury",
    jupiter: "Jupiter",
    venus: "Venus",
    saturn: "Saturn",
    rahu: "Rahu",
    ketu: "Ketu",
  },
  te: {
    sun: "సూర్యుడు",
    moon: "చంద్రుడు",
    mars: "కుజుడు",
    mercury: "బుధుడు",
    jupiter: "గురువు",
    venus: "శుక్రుడు",
    saturn: "శని",
    rahu: "రాహు",
    ketu: "కేతు",
  },
  hi: {
    sun: "सूर्य",
    moon: "चंद्र",
    mars: "मंगल",
    mercury: "बुध",
    jupiter: "गुरु",
    venus: "शुक्र",
    saturn: "शनि",
    rahu: "राहु",
    ketu: "केतु",
  },
  ta: {
    sun: "சூரியன்",
    moon: "சந்திரன்",
    mars: "செவ்வாய்",
    mercury: "புதன்",
    jupiter: "குரு",
    venus: "சுக்ரன்",
    saturn: "சனி",
    rahu: "ராகு",
    ketu: "கேது",
  },
  mr: {
    sun: "सूर्य",
    moon: "चंद्र",
    mars: "मंगळ",
    mercury: "बुध",
    jupiter: "गुरु",
    venus: "शुक्र",
    saturn: "शनि",
    rahu: "राहू",
    ketu: "केतू",
  },
  kn: {
    sun: "ಸೂರ್ಯ",
    moon: "ಚಂದ್ರ",
    mars: "ಮಂಗಳ",
    mercury: "ಬುಧ",
    jupiter: "ಗುರು",
    venus: "ಶುಕ್ರ",
    saturn: "ಶನಿ",
    rahu: "ರಾಹು",
    ketu: "ಕೇತು",
  },
};

export const DASHA_SEQUENCE: PlanetId[] = [
  "ketu",
  "venus",
  "sun",
  "moon",
  "mars",
  "rahu",
  "jupiter",
  "saturn",
  "mercury",
];

export const DASHA_YEARS: Record<PlanetId, number> = {
  ketu: 7,
  venus: 20,
  sun: 6,
  moon: 10,
  mars: 7,
  rahu: 18,
  jupiter: 16,
  saturn: 19,
  mercury: 17,
};

export const SOUTH_INDIAN_GRID: number[][] = [
  [12, 1, 2, 3],
  [11, 0, 0, 4],
  [10, 0, 0, 5],
  [9, 8, 7, 6],
];
