import type { Locale } from "@/lib/types";

export interface CitySeed {
  id: string;
  name: Record<Locale, string>;
  latitude: number;
  longitude: number;
}

/** 161 major Indian cities with localized display names. */
export const CITY_SEEDS: CitySeed[] = [
  {
    id: "hyderabad",
    latitude: 17.385,
    longitude: 78.4867,
    name: {
      en: "Hyderabad",
      hi: "हैदराबाद",
      mr: "हैदराबाद",
      kn: "ಹೈದರಾಬಾದ್",
      te: "హైదరాబాదు",
      ta: "ஹைதராபாத்",
    },
  },
  {
    id: "visakhapatnam",
    latitude: 17.6868,
    longitude: 83.2185,
    name: {
      en: "Visakhapatnam",
      hi: "विशाखापट्टनम",
      mr: "विशाखापट्टणम",
      kn: "ವಿಶಾಖಪಟ್ಟಣ",
      te: "విశాఖపట్నం",
      ta: "விசாகப்பட்டினம்",
    },
  },
  {
    id: "vijayawada",
    latitude: 16.5062,
    longitude: 80.648,
    name: {
      en: "Vijayawada",
      hi: "विजयवाड़ा",
      mr: "विजयवाडा",
      kn: "ವಿಜಯವಾಡ",
      te: "విజయవాడ",
      ta: "விஜயவாடா",
    },
  },
  {
    id: "guntur",
    latitude: 16.3067,
    longitude: 80.4365,
    name: {
      en: "Guntur",
      hi: "गुंटूर",
      mr: "गुंटूर",
      kn: "ಗುಂಟೂರು",
      te: "గుంటూరు",
      ta: "குண்டூர்",
    },
  },
  {
    id: "nellore",
    latitude: 14.4426,
    longitude: 79.9865,
    name: {
      en: "Nellore",
      hi: "नेल्लोर",
      mr: "नेल्लोर",
      kn: "ನೆಲ್ಲೂರು",
      te: "నెల్లూరు",
      ta: "நெல்லூர்",
    },
  },
  {
    id: "kakinada",
    latitude: 16.9891,
    longitude: 82.2475,
    name: {
      en: "Kakinada",
      hi: "काकीनाडा",
      mr: "काकिनाडा",
      kn: "ಕಾಕಿನಾಡ",
      te: "కాకినాడ",
      ta: "காகிநாடா",
    },
  },
  {
    id: "rajahmundry",
    latitude: 17.0005,
    longitude: 81.804,
    name: {
      en: "Rajahmundry",
      hi: "राजमुंदरी",
      mr: "राजमुंद्री",
      kn: "ರಾಜಮಂಡ್ರಿ",
      te: "రాజమండ్రి",
      ta: "ராஜமுந்திரி",
    },
  },
  {
    id: "tirupati",
    latitude: 13.6288,
    longitude: 79.4192,
    name: {
      en: "Tirupati",
      hi: "तिरुपति",
      mr: "तिरुपती",
      kn: "ತಿರುಪತಿ",
      te: "తిరుపతి",
      ta: "திருப்பதி",
    },
  },
  {
    id: "warangal",
    latitude: 17.9689,
    longitude: 79.5941,
    name: {
      en: "Warangal",
      hi: "वारंगल",
      mr: "वारंगळ",
      kn: "ವಾರಂಗಲ್",
      te: "వరంగల్",
      ta: "வரங்கல்",
    },
  },
  {
    id: "karimnagar",
    latitude: 18.4386,
    longitude: 79.1288,
    name: {
      en: "Karimnagar",
      hi: "करीमनगर",
      mr: "करीमनगर",
      kn: "ಕರೀಂನಗರ್",
      te: "కరీంనగర్",
      ta: "கரீம்நகர்",
    },
  },
  {
    id: "nizamabad",
    latitude: 18.6725,
    longitude: 78.0941,
    name: {
      en: "Nizamabad",
      hi: "निज़ामाबाद",
      mr: "निजामाबाद",
      kn: "ನಿಜಾಮಾಬಾದ್",
      te: "నిజామాబాద్",
      ta: "நிஜாமாபாத்",
    },
  },
  {
    id: "kurnool",
    latitude: 15.8281,
    longitude: 78.0373,
    name: {
      en: "Kurnool",
      hi: "कुरनूल",
      mr: "कुरनूल",
      kn: "ಕರ್ನೂಲ್",
      te: "కర్నూలు",
      ta: "கர்னூல்",
    },
  },
  {
    id: "anantapur",
    latitude: 14.6819,
    longitude: 77.6006,
    name: {
      en: "Anantapur",
      hi: "अनंतपुर",
      mr: "अनंतपूर",
      kn: "ಅನಂತಪುರ",
      te: "అనంతపురం",
      ta: "அனந்தபுரம்",
    },
  },
  {
    id: "kadapa",
    latitude: 14.4673,
    longitude: 78.8242,
    name: {
      en: "Kadapa",
      hi: "कडप्पा",
      mr: "कडप्पा",
      kn: "ಕಡಪ",
      te: "కడప",
      ta: "கடப்பா",
    },
  },
  {
    id: "khammam",
    latitude: 17.2473,
    longitude: 80.1514,
    name: {
      en: "Khammam",
      hi: "खम्मम",
      mr: "खम्मम",
      kn: "ಖಮ್ಮಂ",
      te: "ఖమ్మం",
      ta: "கம்மம்",
    },
  },
  {
    id: "mahbubnagar",
    latitude: 16.7488,
    longitude: 77.9854,
    name: {
      en: "Mahbubnagar",
      hi: "महबूबनगर",
      mr: "महबूबनगर",
      kn: "ಮಹಬೂಬ್ನಗರ್",
      te: "మహబూబ్‌నగర్",
      ta: "மஹபூப்நகர்",
    },
  },
  {
    id: "ongole",
    latitude: 15.5057,
    longitude: 80.0499,
    name: {
      en: "Ongole",
      hi: "ओंगोल",
      mr: "ओंगोल",
      kn: "ಒಂಗೋಲ್",
      te: "ఒంగోలు",
      ta: "ஓங்கோல்",
    },
  },
  {
    id: "eluru",
    latitude: 16.7107,
    longitude: 81.0952,
    name: {
      en: "Eluru",
      hi: "एलुरु",
      mr: "एलुरू",
      kn: "ಎಲೂರು",
      te: "ఎలూరు",
      ta: "எலுரு",
    },
  },
  {
    id: "nandyal",
    latitude: 15.477,
    longitude: 78.4836,
    name: {
      en: "Nandyal",
      hi: "नंद्याल",
      mr: "नंद्याळ",
      kn: "ನಂದ್ಯಾಲ್",
      te: "నంద్యాల",
      ta: "நந்தியால்",
    },
  },
  {
    id: "adilabad",
    latitude: 19.6641,
    longitude: 78.532,
    name: {
      en: "Adilabad",
      hi: "आदिलाबाद",
      mr: "आदिलाबाद",
      kn: "ಆದಿಲಾಬಾದ್",
      te: "ఆదిలాబాద్",
      ta: "ஆதிலாபாத்",
    },
  },
  {
    id: "chennai",
    latitude: 13.0827,
    longitude: 80.2707,
    name: {
      en: "Chennai",
      hi: "चेन्नई",
      mr: "चेन्नई",
      kn: "ಚೆನ್ನೈ",
      te: "చెన్నై",
      ta: "சென்னை",
    },
  },
  {
    id: "coimbatore",
    latitude: 11.0168,
    longitude: 76.9558,
    name: {
      en: "Coimbatore",
      hi: "कोयंबटूर",
      mr: "कोयंबतूर",
      kn: "ಕೊಯಮುತ್ತೂರು",
      te: "కోయంబత్తూరు",
      ta: "கோயம்புத்தூர்",
    },
  },
  {
    id: "madurai",
    latitude: 9.9252,
    longitude: 78.1198,
    name: {
      en: "Madurai",
      hi: "मदुरै",
      mr: "मदुराई",
      kn: "ಮದುರೈ",
      te: "మదురై",
      ta: "மதுரை",
    },
  },
  {
    id: "tiruchirappalli",
    latitude: 10.7905,
    longitude: 78.7047,
    name: {
      en: "Tiruchirappalli",
      hi: "तिरुचिरापल्ली",
      mr: "तिरुचिरापल्ली",
      kn: "ತಿರುಚಿರಾಪಳ್ಳಿ",
      te: "తిరుచిరాపల్లి",
      ta: "திருச்சிராப்பள்ளி",
    },
  },
  {
    id: "salem",
    latitude: 11.6643,
    longitude: 78.146,
    name: {
      en: "Salem",
      hi: "सेलम",
      mr: "सेलम",
      kn: "ಸೇಲಂ",
      te: "సేలం",
      ta: "சேலம்",
    },
  },
  {
    id: "tirunelveli",
    latitude: 8.7139,
    longitude: 77.7567,
    name: {
      en: "Tirunelveli",
      hi: "तिरुनेलवेली",
      mr: "तिरुनेलवेली",
      kn: "ತಿರುನೆಲ್ವೇಲಿ",
      te: "తిరునెల్వేలి",
      ta: "திருநெல்வேலி",
    },
  },
  {
    id: "erode",
    latitude: 11.341,
    longitude: 77.7172,
    name: {
      en: "Erode",
      hi: "इरोड",
      mr: "इरोड",
      kn: "ಈರೋಡ್",
      te: "ఈరోడ్",
      ta: "ஈரோடு",
    },
  },
  {
    id: "vellore",
    latitude: 12.9165,
    longitude: 79.1325,
    name: {
      en: "Vellore",
      hi: "वेल्लोर",
      mr: "वेल्लोर",
      kn: "ವೆಲ್ಲೂರು",
      te: "వెల్లూరు",
      ta: "வேலூர்",
    },
  },
  {
    id: "thoothukudi",
    latitude: 8.7642,
    longitude: 78.1348,
    name: {
      en: "Thoothukudi",
      hi: "तूतुकुडी",
      mr: "तूतुकुडी",
      kn: "ತೂತುಕುಡಿ",
      te: "తూతుకుడి",
      ta: "தூத்துக்குடி",
    },
  },
  {
    id: "thanjavur",
    latitude: 10.787,
    longitude: 79.1378,
    name: {
      en: "Thanjavur",
      hi: "तंजावुर",
      mr: "तंजावूर",
      kn: "ತಂಜಾವೂರು",
      te: "తంజావూరు",
      ta: "தஞ்சாவூர்",
    },
  },
  {
    id: "kanchipuram",
    latitude: 12.8342,
    longitude: 79.7036,
    name: {
      en: "Kanchipuram",
      hi: "कांचीपुरम",
      mr: "कांचीपुरम",
      kn: "ಕಾಂಚೀಪುರಂ",
      te: "కాంచీపురం",
      ta: "காஞ்சிபுரம்",
    },
  },
  {
    id: "nagercoil",
    latitude: 8.1833,
    longitude: 77.4119,
    name: {
      en: "Nagercoil",
      hi: "नागरकोइल",
      mr: "नागरकोइल",
      kn: "ನಾಗರಕೋಯಿಲ್",
      te: "నాగర్‌కోయిల్",
      ta: "நாகர்கோவில்",
    },
  },
  {
    id: "tiruppur",
    latitude: 11.1085,
    longitude: 77.3411,
    name: {
      en: "Tiruppur",
      hi: "तिरुप्पुर",
      mr: "तिरुप्पूर",
      kn: "ತಿರುಪ್ಪೂರು",
      te: "తిరుప్పూర్",
      ta: "திருப்பூர்",
    },
  },
  {
    id: "hosur",
    latitude: 12.7409,
    longitude: 77.8253,
    name: {
      en: "Hosur",
      hi: "होसूर",
      mr: "होसूर",
      kn: "ಹೊಸೂರು",
      te: "హోసూర్",
      ta: "ஓசூர்",
    },
  },
  {
    id: "ooty",
    latitude: 11.4064,
    longitude: 76.6932,
    name: {
      en: "Udhagamandalam",
      hi: "ऊटी",
      mr: "ऊटी",
      kn: "ಊಟಿ",
      te: "ఊటి",
      ta: "ஊட்டி",
    },
  },
  {
    id: "rameswaram",
    latitude: 9.2876,
    longitude: 79.3129,
    name: {
      en: "Rameswaram",
      hi: "रामेश्वरम",
      mr: "रामेश्वरम",
      kn: "ರಾಮೇಶ್ವರಂ",
      te: "రామేశ్వరం",
      ta: "ராமேஸ்வரம்",
    },
  },
  {
    id: "tiruvannamalai",
    latitude: 12.2253,
    longitude: 79.0747,
    name: {
      en: "Tiruvannamalai",
      hi: "तिरुवन्नामलाई",
      mr: "तिरुवन्नामलाई",
      kn: "ತಿರುವಣ್ಣಾಮಲೈ",
      te: "తిరువణ్ణామలై",
      ta: "திருவண்ணாமலை",
    },
  },
  {
    id: "puducherry",
    latitude: 11.9416,
    longitude: 79.8083,
    name: {
      en: "Puducherry",
      hi: "पुडुचेरी",
      mr: "पुडुचेरी",
      kn: "ಪುದುಚೇರಿ",
      te: "పుదుచ్చేరి",
      ta: "புதுச்சேரி",
    },
  },
  {
    id: "bengaluru",
    latitude: 12.9716,
    longitude: 77.5946,
    name: {
      en: "Bengaluru",
      hi: "बेंगलुरु",
      mr: "बंगळूर",
      kn: "ಬೆಂಗಳೂರು",
      te: "బెంగళూరు",
      ta: "பெங்களூர்",
    },
  },
  {
    id: "mysuru",
    latitude: 12.2958,
    longitude: 76.6394,
    name: {
      en: "Mysuru",
      hi: "मैसूर",
      mr: "मैसूर",
      kn: "ಮೈಸೂರು",
      te: "మైసూరు",
      ta: "மைசூர்",
    },
  },
  {
    id: "mangaluru",
    latitude: 12.9141,
    longitude: 74.856,
    name: {
      en: "Mangaluru",
      hi: "मंगलुरु",
      mr: "मंगळूर",
      kn: "ಮಂಗಳೂರು",
      te: "మంగళూరు",
      ta: "மங்களூர்",
    },
  },
  {
    id: "hubballi",
    latitude: 15.3647,
    longitude: 75.124,
    name: {
      en: "Hubballi",
      hi: "हुबली",
      mr: "हुबळी",
      kn: "ಹುಬ್ಬಳ್ಳಿ",
      te: "హుబ్బళ్ళి",
      ta: "ஹுப்ளி",
    },
  },
  {
    id: "belagavi",
    latitude: 15.8497,
    longitude: 74.4977,
    name: {
      en: "Belagavi",
      hi: "बेलगावी",
      mr: "बेळगाव",
      kn: "ಬೆಳಗಾವಿ",
      te: "బెలగావి",
      ta: "பெலகாவி",
    },
  },
  {
    id: "kalaburagi",
    latitude: 17.3297,
    longitude: 76.8343,
    name: {
      en: "Kalaburagi",
      hi: "कलबुरगी",
      mr: "कलबुर्गी",
      kn: "ಕಲಬುರಗಿ",
      te: "కలబురగి",
      ta: "கலபுரகி",
    },
  },
  {
    id: "davanagere",
    latitude: 14.4644,
    longitude: 75.9218,
    name: {
      en: "Davanagere",
      hi: "दावणगेरे",
      mr: "दावणगेरे",
      kn: "ದಾವಣಗೆರೆ",
      te: "దావణగెరె",
      ta: "தாவணகேரி",
    },
  },
  {
    id: "ballari",
    latitude: 15.1394,
    longitude: 76.9214,
    name: {
      en: "Ballari",
      hi: "बल्लारी",
      mr: "बल्लारी",
      kn: "ಬಳ್ಳಾರಿ",
      te: "బల్లారి",
      ta: "பள்ளாரி",
    },
  },
  {
    id: "shivamogga",
    latitude: 13.9299,
    longitude: 75.5681,
    name: {
      en: "Shivamogga",
      hi: "शिमोगा",
      mr: "शिवमोग्गा",
      kn: "ಶಿವಮೊಗ್ಗ",
      te: "శివమొగ్గ",
      ta: "சிவமोग்கா",
    },
  },
  {
    id: "tumakuru",
    latitude: 13.3379,
    longitude: 77.1173,
    name: {
      en: "Tumakuru",
      hi: "तुमकुरु",
      mr: "तुमकूर",
      kn: "ತುಮಕೂರು",
      te: "తుమకూరు",
      ta: "துமகூர்",
    },
  },
  {
    id: "raichur",
    latitude: 16.2076,
    longitude: 77.3563,
    name: {
      en: "Raichur",
      hi: "रायचूर",
      mr: "रायचूर",
      kn: "ರಾಯಚೂರು",
      te: "రాయచూరు",
      ta: "ராயச்சூர்",
    },
  },
  {
    id: "hassan",
    latitude: 13.0072,
    longitude: 76.0962,
    name: {
      en: "Hassan",
      hi: "हासन",
      mr: "हासन",
      kn: "ಹಾಸನ",
      te: "హాసన్",
      ta: "ஹாசன்",
    },
  },
  {
    id: "udupi",
    latitude: 13.3409,
    longitude: 74.7421,
    name: {
      en: "Udupi",
      hi: "उडुपी",
      mr: "उडुपी",
      kn: "ಉಡುಪಿ",
      te: "ఉడుపి",
      ta: "உடுப்பி",
    },
  },
  {
    id: "vijayapura",
    latitude: 16.8302,
    longitude: 75.71,
    name: {
      en: "Vijayapura",
      hi: "विजयपुरा",
      mr: "विजापूर",
      kn: "ವಿಜಯಪುರ",
      te: "విజయపుర",
      ta: "விஜயபுரா",
    },
  },
  {
    id: "thiruvananthapuram",
    latitude: 8.5241,
    longitude: 76.9366,
    name: {
      en: "Thiruvananthapuram",
      hi: "तिरुवनंतपुरम",
      mr: "तिरुवनंतपुरम",
      kn: "ತಿರುವನಂತಪುರಂ",
      te: "తిరువనంతపురం",
      ta: "திருவனந்தபுரம்",
    },
  },
  {
    id: "kochi",
    latitude: 9.9312,
    longitude: 76.2673,
    name: {
      en: "Kochi",
      hi: "कोच्चि",
      mr: "कोची",
      kn: "ಕೊಚ್ಚಿ",
      te: "కొచ్చి",
      ta: "கொச்சி",
    },
  },
  {
    id: "kozhikode",
    latitude: 11.2588,
    longitude: 75.7804,
    name: {
      en: "Kozhikode",
      hi: "कोझिकोड",
      mr: "कोझिकोड",
      kn: "ಕೋಳಿಕೋಡ್",
      te: "కోళికోడ్",
      ta: "கோழிக்கோடு",
    },
  },
  {
    id: "thrissur",
    latitude: 10.5276,
    longitude: 76.2144,
    name: {
      en: "Thrissur",
      hi: "त्रिशूर",
      mr: "त्रिशूर",
      kn: "ತ್ರಿಶೂರು",
      te: "త్రిశూర్",
      ta: "திருச்சூர்",
    },
  },
  {
    id: "kollam",
    latitude: 8.8932,
    longitude: 76.6141,
    name: {
      en: "Kollam",
      hi: "कोल्लम",
      mr: "कोल्लम",
      kn: "ಕೊಲ್ಲಂ",
      te: "కొల్లం",
      ta: "கொல்லம்",
    },
  },
  {
    id: "alappuzha",
    latitude: 9.4981,
    longitude: 76.3388,
    name: {
      en: "Alappuzha",
      hi: "अलप्पुझा",
      mr: "अलप्पुझा",
      kn: "ಅಲಪ್ಪುಳ",
      te: "అలప్పుళ",
      ta: "ஆலப்புழா",
    },
  },
  {
    id: "palakkad",
    latitude: 10.7867,
    longitude: 76.6548,
    name: {
      en: "Palakkad",
      hi: "पलक्कड",
      mr: "पलक्कड",
      kn: "ಪಾಲಕ್ಕಾಡ್",
      te: "పాలక్కడ్",
      ta: "பாலக்காடு",
    },
  },
  {
    id: "kannur",
    latitude: 11.8745,
    longitude: 75.3704,
    name: {
      en: "Kannur",
      hi: "कन्नूर",
      mr: "कन्नूर",
      kn: "ಕನ್ನೂರು",
      te: "కన్నూరు",
      ta: "கண்ணூர்",
    },
  },
  {
    id: "kottayam",
    latitude: 9.5916,
    longitude: 76.5222,
    name: {
      en: "Kottayam",
      hi: "कोट्टायम",
      mr: "कोट्टायम",
      kn: "ಕೊಟ್ಟಾಯಂ",
      te: "కొట్టాయం",
      ta: "கோட்டாயம்",
    },
  },
  {
    id: "mumbai",
    latitude: 19.076,
    longitude: 72.8777,
    name: {
      en: "Mumbai",
      hi: "मुंबई",
      mr: "मुंबई",
      kn: "ಮುಂಬೈ",
      te: "ముంబై",
      ta: "மும்பை",
    },
  },
  {
    id: "pune",
    latitude: 18.5204,
    longitude: 73.8567,
    name: {
      en: "Pune",
      hi: "पुणे",
      mr: "पुणे",
      kn: "ಪುಣೆ",
      te: "పూణే",
      ta: "புனே",
    },
  },
  {
    id: "nagpur",
    latitude: 21.1458,
    longitude: 79.0882,
    name: {
      en: "Nagpur",
      hi: "नागपुर",
      mr: "नागपूर",
      kn: "ನಾಗಪುರ",
      te: "నాగపూర్",
      ta: "நாக்பூர்",
    },
  },
  {
    id: "nashik",
    latitude: 19.9975,
    longitude: 73.7898,
    name: {
      en: "Nashik",
      hi: "नासिक",
      mr: "नाशिक",
      kn: "ನಾಸಿಕ್",
      te: "నాసిక్",
      ta: "நாசிக்",
    },
  },
  {
    id: "aurangabad",
    latitude: 19.8762,
    longitude: 75.3433,
    name: {
      en: "Aurangabad",
      hi: "औरंगाबाद",
      mr: "औरंगाबाद",
      kn: "ಔರಂಗಾಬಾದ್",
      te: "ఔరంగాబాద్",
      ta: "ஔரங்காபாத்",
    },
  },
  {
    id: "kolhapur",
    latitude: 16.705,
    longitude: 74.2433,
    name: {
      en: "Kolhapur",
      hi: "कोल्हापुर",
      mr: "कोल्हापूर",
      kn: "ಕೊಲ್ಹಾಪುರ",
      te: "కొల్హాపూర్",
      ta: "கோல்ஹாபூர்",
    },
  },
  {
    id: "thane",
    latitude: 19.2183,
    longitude: 72.9781,
    name: {
      en: "Thane",
      hi: "ठाणे",
      mr: "ठाणे",
      kn: "ಠಾಣೆ",
      te: "ఠాణే",
      ta: "தானே",
    },
  },
  {
    id: "navi-mumbai",
    latitude: 19.033,
    longitude: 73.0297,
    name: {
      en: "Navi Mumbai",
      hi: "नवी मुंबई",
      mr: "नवी मुंबई",
      kn: "ನವಿ ಮುಂಬೈ",
      te: "నవి ముంబై",
      ta: "நவி மும்பை",
    },
  },
  {
    id: "solapur",
    latitude: 17.6599,
    longitude: 75.9064,
    name: {
      en: "Solapur",
      hi: "सोलापुर",
      mr: "सोलापूर",
      kn: "ಸೋಲಾಪುರ",
      te: "సోలాపూర్",
      ta: "சோலாபூர்",
    },
  },
  {
    id: "amravati",
    latitude: 20.9374,
    longitude: 77.7796,
    name: {
      en: "Amravati",
      hi: "अमरावती",
      mr: "अमरावती",
      kn: "ಅಮರಾವತಿ",
      te: "అమరావతి",
      ta: "அமராவதி",
    },
  },
  {
    id: "nanded",
    latitude: 19.1383,
    longitude: 77.321,
    name: {
      en: "Nanded",
      hi: "नांदेड",
      mr: "नांदेड",
      kn: "ನಾಂದೇಡ್",
      te: "నాందేడ్",
      ta: "நாண்டேட்",
    },
  },
  {
    id: "sangli",
    latitude: 16.8524,
    longitude: 74.5815,
    name: {
      en: "Sangli",
      hi: "सांगली",
      mr: "सांगली",
      kn: "ಸಾಂಗ್ಲಿ",
      te: "సాంగ్లి",
      ta: "சாங்கலி",
    },
  },
  {
    id: "jalgaon",
    latitude: 21.0077,
    longitude: 75.5626,
    name: {
      en: "Jalgaon",
      hi: "जलगांव",
      mr: "जळगाव",
      kn: "ಜಲಗಾಂವ್",
      te: "జలగాం",
      ta: "ஜல்கான்",
    },
  },
  {
    id: "akola",
    latitude: 20.7,
    longitude: 77.0082,
    name: {
      en: "Akola",
      hi: "अकोला",
      mr: "अकोला",
      kn: "ಅಕೋಲಾ",
      te: "అకోలా",
      ta: "அகோலா",
    },
  },
  {
    id: "panaji",
    latitude: 15.4909,
    longitude: 73.8278,
    name: {
      en: "Panaji",
      hi: "पणजी",
      mr: "पणजी",
      kn: "ಪಣಜಿ",
      te: "పణజి",
      ta: "பணாஜி",
    },
  },
  {
    id: "ahmedabad",
    latitude: 23.0225,
    longitude: 72.5714,
    name: {
      en: "Ahmedabad",
      hi: "अहमदाबाद",
      mr: "अहमदाबाद",
      kn: "ಅಹಮದಾಬಾದ್",
      te: "అహ్మదాబాద్",
      ta: "அகமதாபாத்",
    },
  },
  {
    id: "surat",
    latitude: 21.1702,
    longitude: 72.8311,
    name: {
      en: "Surat",
      hi: "सूरत",
      mr: "सूरत",
      kn: "ಸೂರತ್",
      te: "సూరత్",
      ta: "சூரத்",
    },
  },
  {
    id: "vadodara",
    latitude: 22.3072,
    longitude: 73.1812,
    name: {
      en: "Vadodara",
      hi: "वडोदरा",
      mr: "वडोदरा",
      kn: "ವಡೋದರ",
      te: "వడోదర",
      ta: "வதோதரா",
    },
  },
  {
    id: "rajkot",
    latitude: 22.3039,
    longitude: 70.8022,
    name: {
      en: "Rajkot",
      hi: "राजकोट",
      mr: "राजकोट",
      kn: "ರಾಜಕೋಟ್",
      te: "రాజ్‌కోట్",
      ta: "ராஜ்கோட்",
    },
  },
  {
    id: "bhavnagar",
    latitude: 21.7645,
    longitude: 72.1519,
    name: {
      en: "Bhavnagar",
      hi: "भावनगर",
      mr: "भावनगर",
      kn: "ಭಾವನಗರ",
      te: "భావనగర్",
      ta: "பாவ்நகர்",
    },
  },
  {
    id: "jamnagar",
    latitude: 22.4707,
    longitude: 70.0577,
    name: {
      en: "Jamnagar",
      hi: "जामनगर",
      mr: "जामनगर",
      kn: "ಜಾಮನಗರ",
      te: "జామ్నగర్",
      ta: "ஜாம்நகர்",
    },
  },
  {
    id: "gandhinagar",
    latitude: 23.2156,
    longitude: 72.6369,
    name: {
      en: "Gandhinagar",
      hi: "गांधीनगर",
      mr: "गांधीनगर",
      kn: "ಗಾಂಧೀನಗರ",
      te: "గాంధీనగర్",
      ta: "காந்திநகர்",
    },
  },
  {
    id: "junagadh",
    latitude: 21.5222,
    longitude: 70.4579,
    name: {
      en: "Junagadh",
      hi: "जूनागढ़",
      mr: "जुनागड",
      kn: "ಜುನಾಗಢ್",
      te: "జూనాగఢ్",
      ta: "ஜூனாகாத்",
    },
  },
  {
    id: "anand",
    latitude: 22.5645,
    longitude: 72.9289,
    name: {
      en: "Anand",
      hi: "आनंद",
      mr: "आनंद",
      kn: "ಆನಂದ್",
      te: "ఆనంద్",
      ta: "ஆனந்த்",
    },
  },
  {
    id: "mehsana",
    latitude: 23.588,
    longitude: 72.3693,
    name: {
      en: "Mehsana",
      hi: "मेहसाणा",
      mr: "मेहसाणा",
      kn: "ಮೇಹಸಾಣ",
      te: "మెహసానా",
      ta: "மேசானா",
    },
  },
  {
    id: "jaipur",
    latitude: 26.9124,
    longitude: 75.7873,
    name: {
      en: "Jaipur",
      hi: "जयपुर",
      mr: "जयपूर",
      kn: "ಜೈಪುರ",
      te: "జైపూర్",
      ta: "ஜெய்ப்பூர்",
    },
  },
  {
    id: "jodhpur",
    latitude: 26.2389,
    longitude: 73.0243,
    name: {
      en: "Jodhpur",
      hi: "जोधपुर",
      mr: "जोधपूर",
      kn: "ಜೋಧಪುರ",
      te: "జోధపూర్",
      ta: "ஜோத்பூர்",
    },
  },
  {
    id: "udaipur",
    latitude: 24.5854,
    longitude: 73.7125,
    name: {
      en: "Udaipur",
      hi: "उदयपुर",
      mr: "उदयपूर",
      kn: "ಉದಯಪುರ",
      te: "ఉదయపూర్",
      ta: "உதயபூர்",
    },
  },
  {
    id: "kota",
    latitude: 25.2138,
    longitude: 75.8648,
    name: {
      en: "Kota",
      hi: "कोटा",
      mr: "कोटा",
      kn: "ಕೋಟಾ",
      te: "కోటా",
      ta: "கோட்டா",
    },
  },
  {
    id: "ajmer",
    latitude: 26.4499,
    longitude: 74.6399,
    name: {
      en: "Ajmer",
      hi: "अजमेर",
      mr: "अजमेर",
      kn: "ಅಜ್ಮೀರ್",
      te: "అజ్మీర్",
      ta: "அஜ்மீர்",
    },
  },
  {
    id: "bikaner",
    latitude: 28.0229,
    longitude: 73.3119,
    name: {
      en: "Bikaner",
      hi: "बीकानेर",
      mr: "बिकानेर",
      kn: "ಬಿಕಾನೇರ್",
      te: "బీకానేర్",
      ta: "பிகானேர்",
    },
  },
  {
    id: "alwar",
    latitude: 27.553,
    longitude: 76.6346,
    name: {
      en: "Alwar",
      hi: "अलवर",
      mr: "अलवर",
      kn: "ಅಲ್ವಾರ್",
      te: "అల్వార్",
      ta: "அல்வார்",
    },
  },
  {
    id: "bharatpur",
    latitude: 27.2152,
    longitude: 77.503,
    name: {
      en: "Bharatpur",
      hi: "भरतपुर",
      mr: "भरतपूर",
      kn: "ಭರತಪುರ",
      te: "భరత్‌పూర్",
      ta: "பரத்பூர்",
    },
  },
  {
    id: "jaisalmer",
    latitude: 26.9157,
    longitude: 70.9083,
    name: {
      en: "Jaisalmer",
      hi: "जैसलमेर",
      mr: "जैसलमेर",
      kn: "ಜೈಸಲ್ಮೇರ್",
      te: "జైసల్మేర్",
      ta: "ஜெய்சல்மேர்",
    },
  },
  {
    id: "new-delhi",
    latitude: 28.6139,
    longitude: 77.209,
    name: {
      en: "New Delhi",
      hi: "नई दिल्ली",
      mr: "नवी दिल्ली",
      kn: "ನವ ದೆಹಲಿ",
      te: "న్యూఢిల్లీ",
      ta: "புது டில்லி",
    },
  },
  {
    id: "lucknow",
    latitude: 26.8467,
    longitude: 80.9462,
    name: {
      en: "Lucknow",
      hi: "लखनऊ",
      mr: "लखनौ",
      kn: "ಲಕ್ನೋ",
      te: "లక్నో",
      ta: "லக்னோ",
    },
  },
  {
    id: "kanpur",
    latitude: 26.4499,
    longitude: 80.3319,
    name: {
      en: "Kanpur",
      hi: "कानपुर",
      mr: "कानपूर",
      kn: "ಕಾನ್ಪುರ್",
      te: "కాన్పూర్",
      ta: "கான்பூர்",
    },
  },
  {
    id: "varanasi",
    latitude: 25.3176,
    longitude: 82.9739,
    name: {
      en: "Varanasi",
      hi: "वाराणसी",
      mr: "वाराणसी",
      kn: "ವಾರಣಾಸಿ",
      te: "వారణాసి",
      ta: "வாரணாசி",
    },
  },
  {
    id: "agra",
    latitude: 27.1767,
    longitude: 78.0081,
    name: {
      en: "Agra",
      hi: "आगरा",
      mr: "आग्रा",
      kn: "ಆಗ್ರಾ",
      te: "ఆగ్రా",
      ta: "ஆக்ரா",
    },
  },
  {
    id: "prayagraj",
    latitude: 25.4358,
    longitude: 81.8463,
    name: {
      en: "Prayagraj",
      hi: "प्रयागराज",
      mr: "प्रयागराज",
      kn: "ಪ್ರಯಾಗ್ರಾಜ್",
      te: "ప్రయాగ్రాజ్",
      ta: "பிரயாக்ராஜ்",
    },
  },
  {
    id: "meerut",
    latitude: 28.9845,
    longitude: 77.7064,
    name: {
      en: "Meerut",
      hi: "मेरठ",
      mr: "मेरठ",
      kn: "ಮೀರಟ್",
      te: "మీరట్",
      ta: "மீரட்",
    },
  },
  {
    id: "ghaziabad",
    latitude: 28.6692,
    longitude: 77.4538,
    name: {
      en: "Ghaziabad",
      hi: "गाज़ियाबाद",
      mr: "गाझियाबाद",
      kn: "ಗಾಜಿಯಾಬಾದ್",
      te: "గాజియాబాద్",
      ta: "காஜியாபாத்",
    },
  },
  {
    id: "noida",
    latitude: 28.5355,
    longitude: 77.391,
    name: {
      en: "Noida",
      hi: "नोएडा",
      mr: "नोएडा",
      kn: "ನೋಯಿಡಾ",
      te: "నోయిడా",
      ta: "நொய்டா",
    },
  },
  {
    id: "gurugram",
    latitude: 28.4595,
    longitude: 77.0266,
    name: {
      en: "Gurugram",
      hi: "गुरुग्राम",
      mr: "गुरुग्राम",
      kn: "ಗುರುಗ್ರಾಮ್",
      te: "గురుగ్రామ్",
      ta: "குருகிராம்",
    },
  },
  {
    id: "faridabad",
    latitude: 28.4089,
    longitude: 77.3178,
    name: {
      en: "Faridabad",
      hi: "फरीदाबाद",
      mr: "फरीदाबाद",
      kn: "ಫರೀದಾಬಾದ್",
      te: "ఫరీదాబాద్",
      ta: "ஃபரிதாபாத்",
    },
  },
  {
    id: "bareilly",
    latitude: 28.367,
    longitude: 79.4304,
    name: {
      en: "Bareilly",
      hi: "बरेली",
      mr: "बरेली",
      kn: "ಬರೇಲಿ",
      te: "బరేలీ",
      ta: "பரேலி",
    },
  },
  {
    id: "gorakhpur",
    latitude: 26.7606,
    longitude: 83.3732,
    name: {
      en: "Gorakhpur",
      hi: "गोरखपुर",
      mr: "गोरखपूर",
      kn: "ಗೋರಖ್ಪುರ್",
      te: "గోరఖ్‌పూర్",
      ta: "கோரக்பூர்",
    },
  },
  {
    id: "aligarh",
    latitude: 27.8974,
    longitude: 78.088,
    name: {
      en: "Aligarh",
      hi: "अलीगढ़",
      mr: "अलीगढ",
      kn: "ಅಲಿಗಢ್",
      te: "అలీగఢ్",
      ta: "அலிகார்",
    },
  },
  {
    id: "mathura",
    latitude: 27.4924,
    longitude: 77.6737,
    name: {
      en: "Mathura",
      hi: "मथुरा",
      mr: "मथुरा",
      kn: "ಮಥುರಾ",
      te: "మథుర",
      ta: "மதுரா",
    },
  },
  {
    id: "ayodhya",
    latitude: 26.7922,
    longitude: 82.1998,
    name: {
      en: "Ayodhya",
      hi: "अयोध्या",
      mr: "अयोध्या",
      kn: "ಅಯೋಧ್ಯ",
      te: "అయోధ్య",
      ta: "அயோத்தியா",
    },
  },
  {
    id: "jhansi",
    latitude: 25.4484,
    longitude: 78.5685,
    name: {
      en: "Jhansi",
      hi: "झांसी",
      mr: "झांसी",
      kn: "ಝಾನ್ಸಿ",
      te: "ఝాన్సీ",
      ta: "ஜான்சி",
    },
  },
  {
    id: "chandigarh",
    latitude: 30.7333,
    longitude: 76.7794,
    name: {
      en: "Chandigarh",
      hi: "चंडीगढ़",
      mr: "चंदीगड",
      kn: "ಚಂಡೀಗಢ",
      te: "చండీగఢ్",
      ta: "சண்டிகர்",
    },
  },
  {
    id: "amritsar",
    latitude: 31.634,
    longitude: 74.8723,
    name: {
      en: "Amritsar",
      hi: "अमृतसर",
      mr: "अमृतसर",
      kn: "ಅಮೃತಸರ",
      te: "అమృత్‌సర్",
      ta: "அம்ரித்சர்",
    },
  },
  {
    id: "ludhiana",
    latitude: 30.901,
    longitude: 75.8573,
    name: {
      en: "Ludhiana",
      hi: "लुधियाना",
      mr: "लुधियाना",
      kn: "ಲುಧಿಯಾನಾ",
      te: "లుధియానా",
      ta: "லூதியானா",
    },
  },
  {
    id: "jalandhar",
    latitude: 31.326,
    longitude: 75.5762,
    name: {
      en: "Jalandhar",
      hi: "जालंधर",
      mr: "जालंधर",
      kn: "ಜಾಲಂಧರ್",
      te: "జలంధర్",
      ta: "ஜலந்தர்",
    },
  },
  {
    id: "patiala",
    latitude: 30.3398,
    longitude: 76.3869,
    name: {
      en: "Patiala",
      hi: "पटियाला",
      mr: "पटियाला",
      kn: "ಪಟಿಯಾಲಾ",
      te: "పటియాలా",
      ta: "பட்டியாலா",
    },
  },
  {
    id: "bathinda",
    latitude: 30.211,
    longitude: 74.9455,
    name: {
      en: "Bathinda",
      hi: "बठिंडा",
      mr: "भटिंडा",
      kn: "ಬಠಿಂಡಾ",
      te: "బఠిండా",
      ta: "பதிண்டா",
    },
  },
  {
    id: "ambala",
    latitude: 30.3782,
    longitude: 76.7767,
    name: {
      en: "Ambala",
      hi: "अंबाला",
      mr: "अंबाळा",
      kn: "ಅಂಬಾಲಾ",
      te: "అంబాలా",
      ta: "அம்பாலா",
    },
  },
  {
    id: "karnal",
    latitude: 29.6857,
    longitude: 76.9905,
    name: {
      en: "Karnal",
      hi: "करनाल",
      mr: "करनाळ",
      kn: "ಕರ್ನಾಲ್",
      te: "కర్నాల్",
      ta: "கர்னால்",
    },
  },
  {
    id: "panipat",
    latitude: 29.3909,
    longitude: 76.9635,
    name: {
      en: "Panipat",
      hi: "पानीपत",
      mr: "पानीपत",
      kn: "ಪಾನಿಪತ್",
      te: "పానీపట్",
      ta: "பானிப்பட்",
    },
  },
  {
    id: "shimla",
    latitude: 31.1048,
    longitude: 77.1734,
    name: {
      en: "Shimla",
      hi: "शिमला",
      mr: "शिमला",
      kn: "ಶಿಮ್ಲಾ",
      te: "షిమ్లా",
      ta: "ஷிம்லா",
    },
  },
  {
    id: "dehradun",
    latitude: 30.3165,
    longitude: 78.0322,
    name: {
      en: "Dehradun",
      hi: "देहरादून",
      mr: "देहरादून",
      kn: "ದೆಹರಾದೂನ್",
      te: "డెహ్రాడూన్",
      ta: "டேராடூன்",
    },
  },
  {
    id: "haridwar",
    latitude: 29.9457,
    longitude: 78.1642,
    name: {
      en: "Haridwar",
      hi: "हरिद्वार",
      mr: "हरिद्वार",
      kn: "ಹರಿದ್ವಾರ",
      te: "హరిద్వార్",
      ta: "ஹரித்வார்",
    },
  },
  {
    id: "rishikesh",
    latitude: 30.0869,
    longitude: 78.2676,
    name: {
      en: "Rishikesh",
      hi: "ऋषिकेश",
      mr: "ऋषिकेश",
      kn: "ಋಷಿಕೇಶ್",
      te: "ఋషికేశ్",
      ta: "஋ஷிகேஷ்",
    },
  },
  {
    id: "kolkata",
    latitude: 22.5726,
    longitude: 88.3639,
    name: {
      en: "Kolkata",
      hi: "कोलकाता",
      mr: "कोलकाता",
      kn: "ಕೋಲ್ಕತಾ",
      te: "కోల్‌కతా",
      ta: "கொல்கத்தா",
    },
  },
  {
    id: "siliguri",
    latitude: 26.7271,
    longitude: 88.3953,
    name: {
      en: "Siliguri",
      hi: "सिलीगुड़ी",
      mr: "सिलीगुडी",
      kn: "ಸಿಲಿಗುರಿ",
      te: "సిలిగురి",
      ta: "சிலிகுரி",
    },
  },
  {
    id: "asansol",
    latitude: 23.6739,
    longitude: 86.9524,
    name: {
      en: "Asansol",
      hi: "आसनसोल",
      mr: "आसनसोल",
      kn: "ಆಸನ್ಸೋಲ್",
      te: "ఆసన్సోల్",
      ta: "அசன்சோல்",
    },
  },
  {
    id: "durgapur",
    latitude: 23.5204,
    longitude: 87.3119,
    name: {
      en: "Durgapur",
      hi: "दुर्गापुर",
      mr: "दुर्गापूर",
      kn: "ದುರ್ಗಾಪುರ",
      te: "దుర్గాపూర్",
      ta: "துர்காபூர்",
    },
  },
  {
    id: "howrah",
    latitude: 22.5958,
    longitude: 88.2636,
    name: {
      en: "Howrah",
      hi: "हावड़ा",
      mr: "हावरा",
      kn: "ಹೌರಾ",
      te: "హౌరా",
      ta: "ஹவுரா",
    },
  },
  {
    id: "darjeeling",
    latitude: 27.036,
    longitude: 88.2627,
    name: {
      en: "Darjeeling",
      hi: "दार्जिलिंग",
      mr: "दार्जिलिंग",
      kn: "ದಾರ್ಜಿಲಿಂಗ್",
      te: "డార్జిలింగ్",
      ta: "டார்ஜிலிங்",
    },
  },
  {
    id: "patna",
    latitude: 25.5941,
    longitude: 85.1376,
    name: {
      en: "Patna",
      hi: "पटना",
      mr: "पटना",
      kn: "ಪಟ್ನಾ",
      te: "పాట్నా",
      ta: "பட்னா",
    },
  },
  {
    id: "gaya",
    latitude: 24.7955,
    longitude: 85.0002,
    name: {
      en: "Gaya",
      hi: "गया",
      mr: "गया",
      kn: "ಗಯಾ",
      te: "గయా",
      ta: "கயா",
    },
  },
  {
    id: "muzaffarpur",
    latitude: 26.1209,
    longitude: 85.3647,
    name: {
      en: "Muzaffarpur",
      hi: "मुज़फ्फरपुर",
      mr: "मुझफ्फरपूर",
      kn: "ಮುಜಫ್ಫರ್‌ಪುರ್",
      te: "ముజఫ్ఫర్‌పూర్",
      ta: "முசாஃபர்பூர்",
    },
  },
  {
    id: "ranchi",
    latitude: 23.3441,
    longitude: 85.3096,
    name: {
      en: "Ranchi",
      hi: "रांची",
      mr: "रांची",
      kn: "ರಾಂಚಿ",
      te: "రాంచి",
      ta: "ராஞ்சி",
    },
  },
  {
    id: "jamshedpur",
    latitude: 22.8046,
    longitude: 86.2029,
    name: {
      en: "Jamshedpur",
      hi: "जमशेदपुर",
      mr: "जमशेदपूर",
      kn: "ಜಂಶೆಡ್ಪುರ್",
      te: "జంషెడ్‌పూర్",
      ta: "ஜம்ஷேட்பூர்",
    },
  },
  {
    id: "dhanbad",
    latitude: 23.7957,
    longitude: 86.4304,
    name: {
      en: "Dhanbad",
      hi: "धनबाद",
      mr: "धनबाद",
      kn: "ಧನಬಾದ್",
      te: "ధన్‌బాద్",
      ta: "தன்பாத்",
    },
  },
  {
    id: "bhubaneswar",
    latitude: 20.2961,
    longitude: 85.8245,
    name: {
      en: "Bhubaneswar",
      hi: "भुवनेश्वर",
      mr: "भुवनेश्वर",
      kn: "ಭುವನೇಶ್ವರ",
      te: "భువనేశ్వర్",
      ta: "புவனேஸ்வர்",
    },
  },
  {
    id: "cuttack",
    latitude: 20.4625,
    longitude: 85.883,
    name: {
      en: "Cuttack",
      hi: "कटक",
      mr: "कटक",
      kn: "ಕಟಕ್",
      te: "కటక్",
      ta: "கட்டக்",
    },
  },
  {
    id: "rourkela",
    latitude: 22.2604,
    longitude: 84.8536,
    name: {
      en: "Rourkela",
      hi: "राउरकेला",
      mr: "राउरकेला",
      kn: "ರೌರ್ಕೆಲಾ",
      te: "రౌర్కెలా",
      ta: "ரௌர்கெலா",
    },
  },
  {
    id: "puri",
    latitude: 19.8135,
    longitude: 85.8312,
    name: {
      en: "Puri",
      hi: "पुरी",
      mr: "पुरी",
      kn: "ಪುರಿ",
      te: "పురి",
      ta: "புரி",
    },
  },
  {
    id: "bhopal",
    latitude: 23.2599,
    longitude: 77.4126,
    name: {
      en: "Bhopal",
      hi: "भोपाल",
      mr: "भोपाळ",
      kn: "ಭೋಪಾಲ್",
      te: "భోపాల్",
      ta: "போபால்",
    },
  },
  {
    id: "indore",
    latitude: 22.7196,
    longitude: 75.8577,
    name: {
      en: "Indore",
      hi: "इंदौर",
      mr: "इंदूर",
      kn: "ಇಂದೋರ್",
      te: "ఇందోర్",
      ta: "இந்தோர்",
    },
  },
  {
    id: "gwalior",
    latitude: 26.2183,
    longitude: 78.1828,
    name: {
      en: "Gwalior",
      hi: "ग्वालियर",
      mr: "ग्वाल्हेर",
      kn: "ಗ್ವಾಲಿಯರ್",
      te: "గ్వాలియర్",
      ta: "குவாலியர்",
    },
  },
  {
    id: "jabalpur",
    latitude: 23.1815,
    longitude: 79.9864,
    name: {
      en: "Jabalpur",
      hi: "जबलपुर",
      mr: "जबलपूर",
      kn: "ಜಬಲ್ಪುರ್",
      te: "జబల్పూర్",
      ta: "ஜபல்பூர்",
    },
  },
  {
    id: "ujjain",
    latitude: 23.1765,
    longitude: 75.7885,
    name: {
      en: "Ujjain",
      hi: "उज्जैन",
      mr: "उज्जैन",
      kn: "ಉಜ್ಜೈನ್",
      te: "ఉజ్జయిని",
      ta: "உஜ்ஜைன்",
    },
  },
  {
    id: "raipur",
    latitude: 21.2514,
    longitude: 81.6296,
    name: {
      en: "Raipur",
      hi: "रायपुर",
      mr: "रायपूर",
      kn: "ರಾಯ್ಪುರ್",
      te: "రాయ్‌పూర్",
      ta: "ராய்ப்பூர்",
    },
  },
  {
    id: "bilaspur",
    latitude: 22.0797,
    longitude: 82.1391,
    name: {
      en: "Bilaspur",
      hi: "बिलासपुर",
      mr: "बिलासपूर",
      kn: "ಬಿಲಾಸ್ಪುರ್",
      te: "బిలాస్పూర్",
      ta: "பிலாஸ்பூர்",
    },
  },
  {
    id: "guwahati",
    latitude: 26.1445,
    longitude: 91.7362,
    name: {
      en: "Guwahati",
      hi: "गुवाहाटी",
      mr: "गुवाहाटी",
      kn: "ಗುವಾಹಾಟಿ",
      te: "గువహాటి",
      ta: "குவஹாத்தி",
    },
  },
  {
    id: "shillong",
    latitude: 25.5788,
    longitude: 91.8933,
    name: {
      en: "Shillong",
      hi: "शिलांग",
      mr: "शिलाँग",
      kn: "ಶಿಲ್ಲಾಂಗ್",
      te: "షిల్లాంగ్",
      ta: "ஷில்லாங்",
    },
  },
  {
    id: "imphal",
    latitude: 24.817,
    longitude: 93.9368,
    name: {
      en: "Imphal",
      hi: "इंफाल",
      mr: "इंफाळ",
      kn: "ಇಂಫಾಲ್",
      te: "ఇంఫాల్",
      ta: "இம்பால்",
    },
  },
  {
    id: "agartala",
    latitude: 23.8315,
    longitude: 91.2868,
    name: {
      en: "Agartala",
      hi: "अगरतला",
      mr: "अगरतला",
      kn: "ಅಗರ್ತಲಾ",
      te: "అగర్తలా",
      ta: "அகர்தலா",
    },
  },
  {
    id: "aizawl",
    latitude: 23.7271,
    longitude: 92.7176,
    name: {
      en: "Aizawl",
      hi: "आइज़ोल",
      mr: "आइझोल",
      kn: "ಐಜೋಲ್",
      te: "ఐజ్వాల్",
      ta: "ஐசால்",
    },
  },
  {
    id: "kohima",
    latitude: 25.6751,
    longitude: 94.1086,
    name: {
      en: "Kohima",
      hi: "कोहिमा",
      mr: "कोहिमा",
      kn: "ಕೋಹಿಮಾ",
      te: "కోహిమా",
      ta: "கோஹிமா",
    },
  },
  {
    id: "gangtok",
    latitude: 27.3389,
    longitude: 88.6065,
    name: {
      en: "Gangtok",
      hi: "गंगटोक",
      mr: "गंगटोक",
      kn: "ಗಂಗ್ಟೋಕ್",
      te: "గంగ్టోక్",
      ta: "கங்க்டோக்",
    },
  },
  {
    id: "silchar",
    latitude: 24.8333,
    longitude: 92.7789,
    name: {
      en: "Silchar",
      hi: "सिलचर",
      mr: "सिलचर",
      kn: "ಸಿಲ್ಚಾರ್",
      te: "సిల్చర్",
      ta: "சில்சார்",
    },
  },
  {
    id: "srinagar",
    latitude: 34.0837,
    longitude: 74.7973,
    name: {
      en: "Srinagar",
      hi: "श्रीनगर",
      mr: "श्रीनगर",
      kn: "ಶ್ರೀನಗರ",
      te: "శ్రీనగర్",
      ta: "ஸ்ரீநகர்",
    },
  },
  {
    id: "jammu",
    latitude: 32.7266,
    longitude: 74.857,
    name: {
      en: "Jammu",
      hi: "जम्मू",
      mr: "जम्मू",
      kn: "ಜಮ್ಮು",
      te: "జమ్మూ",
      ta: "ஜம்மு",
    },
  },
  {
    id: "leh",
    latitude: 34.1526,
    longitude: 77.577,
    name: {
      en: "Leh",
      hi: "लेह",
      mr: "लेह",
      kn: "ಲೇಹ್",
      te: "లేహ్",
      ta: "லே",
    },
  },
  {
    id: "port-blair",
    latitude: 11.6234,
    longitude: 92.7265,
    name: {
      en: "Port Blair",
      hi: "पोर्ट ब्लेयर",
      mr: "पोर्ट ब्लेअर",
      kn: "ಪೋರ್ಟ್ ಬ್ಲೇರ್",
      te: "పోర్ట్ బ్లేర్",
      ta: "போர்ட் பிளேயர்",
    },
  },
  {
    id: "shirdi",
    latitude: 19.7645,
    longitude: 74.477,
    name: {
      en: "Shirdi",
      hi: "शिरडी",
      mr: "शिर्डी",
      kn: "ಶಿರಡಿ",
      te: "షిర్డి",
      ta: "ஷிர்டி",
    },
  },
];
